<a href="https://colab.research.google.com/github/Laya-Shree/Customer_Purchase_Prediction/blob/main/Purchase_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/Social_Network_Ads.csv")
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
data['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [ ]:
gender = pd.get_dummies(data['Gender'],drop_first=True) ## drop_first deletes the first column
gender

Male
0       1
1       1
2       0
3       0
4       1
..    ...
395     0
396     1
397     0
398     1
399     0

[400 rows x 1 columns]

In [ ]:
data['Gender'] = gender
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [ ]:
data.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [ ]:
x = data[['Gender','Age','EstimatedSalary']]
y = data['Purchased']

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=6)

In [ ]:
y.value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [ ]:
ytrain.value_counts()

0    205
1    115
Name: Purchased, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
log = LogisticRegression()
knn = KNeighborsClassifier(n_neighbors=3)
log.fit(xtrain,ytrain)
knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
log_yp = log.predict(xtest)
knn_yp = knn.predict(xtest)

In [ ]:
log_yp

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [ ]:
knn_yp

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0])

In [ ]:
ytest.values

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,f1_score

In [ ]:
cm_knn = confusion_matrix(ytest,knn_yp)
cm_log = confusion_matrix(ytest,log_yp)

In [ ]:
cm_knn

array([[49,  3],
       [ 2, 26]])

In [ ]:
cm_log

array([[49,  3],
       [ 6, 22]])

In [ ]:
as_knn = accuracy_score(ytest,knn_yp)
as_log = accuracy_score(ytest,log_yp)
ps_knn = precision_score(ytest,knn_yp)
ps_log = precision_score(ytest,log_yp)
rs_knn = recall_score(ytest,knn_yp)
rs_log = recall_score(ytest,log_yp)
f1_knn = f1_score(ytest,knn_yp)
f1_log = f1_score(ytest,log_yp)

In [ ]:
print(as_knn)

0.9375


In [ ]:
print(as_log)

0.8875


In [ ]:
print(ps_knn)

0.896551724137931


In [ ]:
print(ps_log)

0.88


In [ ]:
print(rs_knn)

0.9285714285714286


In [ ]:
print(rs_log)

0.7857142857142857


In [ ]:
print(f1_knn)

0.912280701754386


In [ ]:
print(f1_log)

0.830188679245283


In [ ]:
## test a new sample
knn.predict([[1,20,30000]]) ## it is not scaled data where as the data given for training is scaled data

array([1])

In [ ]:
sample = np.array([[1,20,30000]]) ## it is scaled
sample = sc.transform(sample)
sample

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


array([[ 1.02020406, -1.6862843 , -1.16703281]])

In [ ]:
knn.predict(sample)

array([0])